In [ ]:
# DATA CLEANING FOR AN AIRBNB USING PANDAS

In [ ]:
import pandas as pd

In [ ]:
data = pd.read_csv(r"C:\Users\User\Desktop\mypython\data-set-projects-yt\Airbnb_Open_Data.csv")

In [ ]:
data.head()

In [ ]:
# for checking all the columns
data.columns

In [ ]:
data.info()

In [ ]:
data["license"]

In [ ]:
# DATA CLEANING PROCESSES, WE WILL FOLLOW
"""
DELETING REDUNDANT COLUMNS
RENAMING THE COLUMNS
DROPPING DUPLICATES
CLEANING INDIVIDUAL COLUMNS
REMOVE THE NAN VALUES FROM THE DATA SET
CHECK FOR SOME MORE TRANSFORMATION
"""

In [ ]:
#PERFORMING THE FIRST TASK
# DELETING REDUNDANT COLUMNS

In [ ]:
data.columns

In [ ]:
# STEPS IN PERFORMING THIS TASK
"""
    WE WANT TO CREATE A LIST OF COLUMNS WE WANT TO SAVE AND LIST OF COLUMNS
    WE WANT TO DROP
"""

In [ ]:
columns_to_keep = ['NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review']

columns_to_drop = ['reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules', 'license', 'id']

In [ ]:
len(columns_to_keep)

In [ ]:
len(columns_to_drop)

In [31]:
df = data[columns_to_keep]
df

,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews,last review
0,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,strict,Private room,2020.0,$966,$193,10.0,9.0,10/19/2021
1,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,False,moderate,Entire home/apt,2007.0,$142,$28,30.0,45.0,5/21/2022
2,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,US,True,flexible,Private room,2005.0,$620,$124,3.0,0.0,NaN
3,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,US,True,moderate,Entire home/apt,2005.0,$368,$74,30.0,270.0,7/5/2019
4,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,False,moderate,Entire home/apt,2009.0,$204,$41,10.0,9.0,11/19/2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,US,False,flexible,Private room,2003.0,$844,$169,1.0,0.0,NaN
102595,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,US,True,moderate,Private room,2016.0,$837,$167,1.0,1.0,7/6/2015
102596,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,US,True,moderate,Private room,2009.0,$988,$198,3.0,0.0,NaN
102597,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,US,True,strict,Entire home/apt,2015.0,$546,$109,2.0,5.0,10/11/2015
102598,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,US,False,flexible,Entire home/apt,2010.0,"$1,032",$206,1.0,0.0,NaN

In [34]:
# 2nd method, dropping columns

In [35]:
data.columns

Index(['id', 'NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review', 'reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules', 'license'],
      dtype='object')

In [40]:
data.drop(columns = columns_to_drop, inplace = True)

In [41]:
data.shape

(102599, 19)

In [ ]:
# DATA CLEANING PROCESSES, WE WILL FOLLOW
"""
DELETING REDUNDANT COLUMNS (done)
RENAMING THE COLUMNS
DROPPING DUPLICATES
CLEANING INDIVIDUAL COLUMNS
REMOVE THE NAN VALUES FROM THE DATA SET
CHECK FOR SOME MORE TRANSFORMATION
"""

In [44]:
# RENAMING THR COLUMNS
data.columns

Index(['NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review'],
      dtype='object')

In [46]:
# we want tot raname the name column to lowercase

data.rename(columns = {"NAME": "Name"}, inplace=True)

In [48]:
data.columns

Index(['Name', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review'],
      dtype='object')

In [50]:
# we can decide o change all the columns to capital letter through iteration

In [52]:
new_columns_names = []
for i in data.columns:
    new_columns_names.append(i.upper())

In [57]:
type(new_columns_names)

list

In [58]:
new_dataframe_to_modify = data.copy()

In [59]:
new_dataframe_to_modify.columns = new_columns_names

In [61]:
data = new_dataframe_to_modify

In [63]:
data.columns

Index(['NAME', 'HOST ID', 'HOST_IDENTITY_VERIFIED', 'HOST NAME',
       'NEIGHBOURHOOD GROUP', 'NEIGHBOURHOOD', 'LAT', 'LONG', 'COUNTRY',
       'COUNTRY CODE', 'INSTANT_BOOKABLE', 'CANCELLATION_POLICY', 'ROOM TYPE',
       'CONSTRUCTION YEAR', 'PRICE', 'SERVICE FEE', 'MINIMUM NIGHTS',
       'NUMBER OF REVIEWS', 'LAST REVIEW'],
      dtype='object')

In [64]:
"""
DELETING REDUNDANT COLUMNS (done)
RENAMING THE COLUMNS (done)
DROPPING DUPLICATES (done)
CLEANING INDIVIDUAL COLUMNS
REMOVE THE NAN VALUES FROM THE DATA SET
CHECK FOR SOME MORE TRANSFORMATION
"""

'\nDELETING REDUNDANT COLUMNS (done)\nRENAMING THE COLUMNS (done)\nDROPPING DUPLICATES\nCLEANING INDIVIDUAL COLUMNS\nREMOVE THE NAN VALUES FROM THE DATA SET\nCHECK FOR SOME MORE TRANSFORMATION\n'

In [66]:
# DROPPING DUPLICATE
data.duplicated()

0         False
1         False
2         False
3         False
4         False
          ...
102594     True
102595     True
102596     True
102597     True
102598     True
Length: 102599, dtype: bool

In [70]:
data.drop_duplicates(inplace = True)

In [71]:
data

,NAME,HOST ID,HOST_IDENTITY_VERIFIED,HOST NAME,NEIGHBOURHOOD GROUP,NEIGHBOURHOOD,LAT,LONG,COUNTRY,COUNTRY CODE,INSTANT_BOOKABLE,CANCELLATION_POLICY,ROOM TYPE,CONSTRUCTION YEAR,PRICE,SERVICE FEE,MINIMUM NIGHTS,NUMBER OF REVIEWS,LAST REVIEW
0,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,strict,Private room,2020.0,$966,$193,10.0,9.0,10/19/2021
1,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,False,moderate,Entire home/apt,2007.0,$142,$28,30.0,45.0,5/21/2022
2,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,US,True,flexible,Private room,2005.0,$620,$124,3.0,0.0,NaN
3,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,US,True,moderate,Entire home/apt,2005.0,$368,$74,30.0,270.0,7/5/2019
4,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,False,moderate,Entire home/apt,2009.0,$204,$41,10.0,9.0,11/19/2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102053,Cozy bright room near Prospect Park,77326652202,unconfirmed,Mariam,Brooklyn,Flatbush,40.64945,-73.96108,United States,US,True,moderate,Private room,NaN,$696,NaN,7.0,12.0,3/27/2019
102054,Private Bedroom with Amazing Rooftop View,45936254757,verified,Trey,Brooklyn,Bushwick,40.69872,-73.92718,United States,US,False,flexible,Private room,NaN,$909,NaN,1.0,19.0,8/31/2017
102055,Pretty Brooklyn One-Bedroom for 2 to 4 people,23801060917,verified,Michael,Brooklyn,Bedford-Stuyvesant,40.67810,-73.90822,United States,US,True,moderate,Entire home/apt,NaN,$387,NaN,2.0,50.0,6/26/2019
102056,Room & private bathroom in historic Harlem,15593031571,unconfirmed,Shireen,Manhattan,Harlem,40.81248,-73.94317,United States,US,True,strict,Private room,NaN,$848,NaN,2.0,0.0,NaN
102057,Rosalee Stewart,93578954226,verified,Stanley,Manhattan,Harlem,40.81315,-73.94747,United States,US,False,flexible,Entire home/apt,2011.0,"$1,128",NaN,4.0,22.0,6/15/2019

In [73]:
# This confirms that we have sucessfully dropped the duplicates in the data, since it gives us zero
data.duplicated().sum()

0

In [74]:
"""
DELETING REDUNDANT COLUMNS (done)
RENAMING THE COLUMNS (done)
DROPPING DUPLICATES (done)
REMOVE THE NAN VALUES FROM THE DATA SET
CLEANING INDIVIDUAL COLUMNS
CHECK FOR SOME MORE TRANSFORMATION
"""

'\nDELETING REDUNDANT COLUMNS (done)\nRENAMING THE COLUMNS (done)\nDROPPING DUPLICATES (done)\nCLEANING INDIVIDUAL COLUMNS\nREMOVE THE NAN VALUES FROM THE DATA SET\nCHECK FOR SOME MORE TRANSFORMATION\n'

In [82]:
# REMOVING THE NAN VALUES
data.isna().sum() # this reveals the amount of nan per column in the data set

NAME                        250
HOST ID                       0
HOST_IDENTITY_VERIFIED      289
HOST NAME                   404
NEIGHBOURHOOD GROUP          29
NEIGHBOURHOOD                16
LAT                           8
LONG                          8
COUNTRY                     532
COUNTRY CODE                131
INSTANT_BOOKABLE            105
CANCELLATION_POLICY          76
ROOM TYPE                     0
CONSTRUCTION YEAR           214
PRICE                       247
SERVICE FEE                 273
MINIMUM NIGHTS              400
NUMBER OF REVIEWS           183
LAST REVIEW               15832
dtype: int64

In [83]:
data.drop(columns = ["LAST REVIEW"], inplace = True)

In [84]:
data.isna().sum()

NAME                      250
HOST ID                     0
HOST_IDENTITY_VERIFIED    289
HOST NAME                 404
NEIGHBOURHOOD GROUP        29
NEIGHBOURHOOD              16
LAT                         8
LONG                        8
COUNTRY                   532
COUNTRY CODE              131
INSTANT_BOOKABLE          105
CANCELLATION_POLICY        76
ROOM TYPE                   0
CONSTRUCTION YEAR         214
PRICE                     247
SERVICE FEE               273
MINIMUM NIGHTS            400
NUMBER OF REVIEWS         183
dtype: int64

In [86]:
data.dropna(inplace= True) # this drops the nan values

In [87]:
data.isna().sum()

NAME                      0
HOST ID                   0
HOST_IDENTITY_VERIFIED    0
HOST NAME                 0
NEIGHBOURHOOD GROUP       0
NEIGHBOURHOOD             0
LAT                       0
LONG                      0
COUNTRY                   0
COUNTRY CODE              0
INSTANT_BOOKABLE          0
CANCELLATION_POLICY       0
ROOM TYPE                 0
CONSTRUCTION YEAR         0
PRICE                     0
SERVICE FEE               0
MINIMUM NIGHTS            0
NUMBER OF REVIEWS         0
dtype: int64

In [88]:
"""
DELETING REDUNDANT COLUMNS (done)
RENAMING THE COLUMNS (done)
DROPPING DUPLICATES (done)
REMOVE THE NAN VALUES FROM THE DATA SET (done)
CLEANING INDIVIDUAL COLUMNS 
CHECK FOR SOME MORE TRANSFORMATION
"""

'\nDELETING REDUNDANT COLUMNS (done)\nRENAMING THE COLUMNS (done)\nDROPPING DUPLICATES (done)\nREMOVE THE NAN VALUES FROM THE DATA SET (done)\nCLEANING INDIVIDUAL COLUMNS\nCHECK FOR SOME MORE TRANSFORMATION\n'

In [103]:
# cleaning individual columns
# we want to change the case of the host identity verified to upper case
# data["HOST_IDENTITY_VERIFIED"]
# data["HOST_IDENTITY_VERIFIED"].str.upper()
# to save the changes
data["HOST_IDENTITY_VERIFIED"]=data["HOST_IDENTITY_VERIFIED"].str.upper()

In [105]:
data["INSTANT_BOOKABLE"]

0         False
1         False
4         False
5          True
7         False
          ...
102029    False
102030     True
102031     True
102032    False
102040     True
Name: INSTANT_BOOKABLE, Length: 99342, dtype: object

In [107]:
# change the true or false to 1's and 0's
data["INSTANT_BOOKABLE"].apply(lambda x: 1 if x == True else 0)

0         0
1         0
4         0
5         1
7         0
         ..
102029    0
102030    1
102031    1
102032    0
102040    1
Name: INSTANT_BOOKABLE, Length: 99342, dtype: int64

In [109]:
data["INSTANT_BOOKABLE"] = data["INSTANT_BOOKABLE"].apply(lambda x: 1 if x == True else 0)

In [110]:
data

,NAME,HOST ID,HOST_IDENTITY_VERIFIED,HOST NAME,NEIGHBOURHOOD GROUP,NEIGHBOURHOOD,LAT,LONG,COUNTRY,COUNTRY CODE,INSTANT_BOOKABLE,CANCELLATION_POLICY,ROOM TYPE,CONSTRUCTION YEAR,PRICE,SERVICE FEE,MINIMUM NIGHTS,NUMBER OF REVIEWS
0,Clean & quiet apt home by the park,80014485718,UNCONFIRMED,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,0,strict,Private room,2020.0,$966,$193,10.0,9.0
1,Skylit Midtown Castle,52335172823,VERIFIED,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,0,moderate,Entire home/apt,2007.0,$142,$28,30.0,45.0
4,Entire Apt: Spacious Studio/Loft by central park,92037596077,VERIFIED,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,0,moderate,Entire home/apt,2009.0,$204,$41,10.0,9.0
5,Large Cozy 1 BR Apartment In Midtown East,45498551794,VERIFIED,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,US,1,flexible,Entire home/apt,2013.0,$577,$115,3.0,74.0
7,BlissArtsSpace!,90821839709,UNCONFIRMED,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,0,moderate,Private room,2009.0,"$1,060",$212,45.0,49.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102029,Cozy room in a 2B with backyard access,5155155913,UNCONFIRMED,Cristina,Queens,Astoria,40.76987,-73.92679,United States,US,0,flexible,Private room,2018.0,$822,$164,1.0,9.0
102030,An East Williamsburg Delight,71564706996,VERIFIED,Petra,Brooklyn,Bedford-Stuyvesant,40.68335,-73.91222,United States,US,1,moderate,Private room,2015.0,$455,$91,4.0,36.0
102031,Cozy bedroom in williamsburg,83101851929,VERIFIED,Russell,Brooklyn,Williamsburg,40.70870,-73.96710,United States,US,1,flexible,Private room,2020.0,"$1,078",$216,1.0,58.0
102032,Spacious Room w/ 2 Bed,69037598918,UNCONFIRMED,Christine,Queens,Bayside,40.75047,-73.75349,United States,US,0,moderate,Private room,2007.0,$103,$21,7.0,40.0
102040,"Room in Queens, NY, near LGA.",56457739998,VERIFIED,Sonia,Queens,East Elmhurst,40.76245,-73.87938,United States,US,1,strict,Private room,2022.0,$982,$196,1.0,239.0

In [119]:
type(data["INSTANT_BOOKABLE"][15])
# this will display error because we no longer have 15 after removing nan values

numpy.int64

In [117]:
#doing this eliminate that initial error
data.reset_index(inplace = True)

In [118]:
data

,index,NAME,HOST ID,HOST_IDENTITY_VERIFIED,HOST NAME,NEIGHBOURHOOD GROUP,NEIGHBOURHOOD,LAT,LONG,COUNTRY,COUNTRY CODE,INSTANT_BOOKABLE,CANCELLATION_POLICY,ROOM TYPE,CONSTRUCTION YEAR,PRICE,SERVICE FEE,MINIMUM NIGHTS,NUMBER OF REVIEWS
0,0,Clean & quiet apt home by the park,80014485718,UNCONFIRMED,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,0,strict,Private room,2020.0,$966,$193,10.0,9.0
1,1,Skylit Midtown Castle,52335172823,VERIFIED,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,0,moderate,Entire home/apt,2007.0,$142,$28,30.0,45.0
2,4,Entire Apt: Spacious Studio/Loft by central park,92037596077,VERIFIED,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,0,moderate,Entire home/apt,2009.0,$204,$41,10.0,9.0
3,5,Large Cozy 1 BR Apartment In Midtown East,45498551794,VERIFIED,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,US,1,flexible,Entire home/apt,2013.0,$577,$115,3.0,74.0
4,7,BlissArtsSpace!,90821839709,UNCONFIRMED,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,0,moderate,Private room,2009.0,"$1,060",$212,45.0,49.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99337,102029,Cozy room in a 2B with backyard access,5155155913,UNCONFIRMED,Cristina,Queens,Astoria,40.76987,-73.92679,United States,US,0,flexible,Private room,2018.0,$822,$164,1.0,9.0
99338,102030,An East Williamsburg Delight,71564706996,VERIFIED,Petra,Brooklyn,Bedford-Stuyvesant,40.68335,-73.91222,United States,US,1,moderate,Private room,2015.0,$455,$91,4.0,36.0
99339,102031,Cozy bedroom in williamsburg,83101851929,VERIFIED,Russell,Brooklyn,Williamsburg,40.70870,-73.96710,United States,US,1,flexible,Private room,2020.0,"$1,078",$216,1.0,58.0
99340,102032,Spacious Room w/ 2 Bed,69037598918,UNCONFIRMED,Christine,Queens,Bayside,40.75047,-73.75349,United States,US,0,moderate,Private room,2007.0,$103,$21,7.0,40.0
99341,102040,"Room in Queens, NY, near LGA.",56457739998,VERIFIED,Sonia,Queens,East Elmhurst,40.76245,-73.87938,United States,US,1,strict,Private room,2022.0,$982,$196,1.0,239.0

In [120]:
"""
DELETING REDUNDANT COLUMNS (done)
RENAMING THE COLUMNS (done)
DROPPING DUPLICATES (done)
REMOVE THE NAN VALUES FROM THE DATA SET (done)
CLEANING INDIVIDUAL COLUMNS  (done)
CHECK FOR SOME MORE TRANSFORMATION
"""

'\nDELETING REDUNDANT COLUMNS (done)\nRENAMING THE COLUMNS (done)\nDROPPING DUPLICATES (done)\nREMOVE THE NAN VALUES FROM THE DATA SET (done)\nCLEANING INDIVIDUAL COLUMNS  (done)\nCHECK FOR SOME MORE TRANSFORMATION\n'

In [122]:
data['PRICE'][15]

'$1,020 '

In [123]:
type(data['PRICE'][15])

str

In [124]:
data['PRICE'].str.lstrip('$')

0          966
1          142
2          204
3          577
4        1,060
          ...
99337      822
99338      455
99339    1,078
99340      103
99341      982
Name: PRICE, Length: 99342, dtype: object

In [125]:
# WE WANT TO STRIP THE DOLLAR SIGN FROM THE PRICE AND CONVERT IT TO INT, SINCE IT IS STRING BEFORE
data['PRICE'] = data['PRICE'].str.lstrip('$')

In [127]:
type(data['PRICE'][15])

str

In [132]:
data['PRICE'].str.replace(',', '').astype(int)

0         966
1         142
2         204
3         577
4        1060
         ...
99337     822
99338     455
99339    1078
99340     103
99341     982
Name: PRICE, Length: 99342, dtype: int32

In [133]:
data['PRICE'] = data['PRICE'].str.replace(',', '').astype(int)

In [134]:
data['PRICE']

0         966
1         142
2         204
3         577
4        1060
         ...
99337     822
99338     455
99339    1078
99340     103
99341     982
Name: PRICE, Length: 99342, dtype: int32

In [135]:
type(data['PRICE'][15])

numpy.int32

In [136]:
data

,index,NAME,HOST ID,HOST_IDENTITY_VERIFIED,HOST NAME,NEIGHBOURHOOD GROUP,NEIGHBOURHOOD,LAT,LONG,COUNTRY,COUNTRY CODE,INSTANT_BOOKABLE,CANCELLATION_POLICY,ROOM TYPE,CONSTRUCTION YEAR,PRICE,SERVICE FEE,MINIMUM NIGHTS,NUMBER OF REVIEWS
0,0,Clean & quiet apt home by the park,80014485718,UNCONFIRMED,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,0,strict,Private room,2020.0,966,$193,10.0,9.0
1,1,Skylit Midtown Castle,52335172823,VERIFIED,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,0,moderate,Entire home/apt,2007.0,142,$28,30.0,45.0
2,4,Entire Apt: Spacious Studio/Loft by central park,92037596077,VERIFIED,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,0,moderate,Entire home/apt,2009.0,204,$41,10.0,9.0
3,5,Large Cozy 1 BR Apartment In Midtown East,45498551794,VERIFIED,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,US,1,flexible,Entire home/apt,2013.0,577,$115,3.0,74.0
4,7,BlissArtsSpace!,90821839709,UNCONFIRMED,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,0,moderate,Private room,2009.0,1060,$212,45.0,49.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99337,102029,Cozy room in a 2B with backyard access,5155155913,UNCONFIRMED,Cristina,Queens,Astoria,40.76987,-73.92679,United States,US,0,flexible,Private room,2018.0,822,$164,1.0,9.0
99338,102030,An East Williamsburg Delight,71564706996,VERIFIED,Petra,Brooklyn,Bedford-Stuyvesant,40.68335,-73.91222,United States,US,1,moderate,Private room,2015.0,455,$91,4.0,36.0
99339,102031,Cozy bedroom in williamsburg,83101851929,VERIFIED,Russell,Brooklyn,Williamsburg,40.70870,-73.96710,United States,US,1,flexible,Private room,2020.0,1078,$216,1.0,58.0
99340,102032,Spacious Room w/ 2 Bed,69037598918,UNCONFIRMED,Christine,Queens,Bayside,40.75047,-73.75349,United States,US,0,moderate,Private room,2007.0,103,$21,7.0,40.0
99341,102040,"Room in Queens, NY, near LGA.",56457739998,VERIFIED,Sonia,Queens,East Elmhurst,40.76245,-73.87938,United States,US,1,strict,Private room,2022.0,982,$196,1.0,239.0

In [137]:
# we want to clean service fee, by converting the string to int and removing the dollar sign
data['SERVICE FEE']

0        $193
1         $28
2         $41
3        $115
4        $212
         ...
99337    $164
99338     $91
99339    $216
99340     $21
99341    $196
Name: SERVICE FEE, Length: 99342, dtype: object

In [138]:
data['SERVICE FEE'].str.replace('$', '').astype(int)

0        193
1         28
2         41
3        115
4        212
        ...
99337    164
99338     91
99339    216
99340     21
99341    196
Name: SERVICE FEE, Length: 99342, dtype: int32

In [139]:
data['SERVICE FEE'] = data['SERVICE FEE'].str.replace('$', '').astype(int)

In [140]:
data['SERVICE FEE']

0        193
1         28
2         41
3        115
4        212
        ...
99337    164
99338     91
99339    216
99340     21
99341    196
Name: SERVICE FEE, Length: 99342, dtype: int32

In [141]:
data

,index,NAME,HOST ID,HOST_IDENTITY_VERIFIED,HOST NAME,NEIGHBOURHOOD GROUP,NEIGHBOURHOOD,LAT,LONG,COUNTRY,COUNTRY CODE,INSTANT_BOOKABLE,CANCELLATION_POLICY,ROOM TYPE,CONSTRUCTION YEAR,PRICE,SERVICE FEE,MINIMUM NIGHTS,NUMBER OF REVIEWS
0,0,Clean & quiet apt home by the park,80014485718,UNCONFIRMED,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,0,strict,Private room,2020.0,966,193,10.0,9.0
1,1,Skylit Midtown Castle,52335172823,VERIFIED,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,0,moderate,Entire home/apt,2007.0,142,28,30.0,45.0
2,4,Entire Apt: Spacious Studio/Loft by central park,92037596077,VERIFIED,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,0,moderate,Entire home/apt,2009.0,204,41,10.0,9.0
3,5,Large Cozy 1 BR Apartment In Midtown East,45498551794,VERIFIED,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,US,1,flexible,Entire home/apt,2013.0,577,115,3.0,74.0
4,7,BlissArtsSpace!,90821839709,UNCONFIRMED,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,0,moderate,Private room,2009.0,1060,212,45.0,49.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99337,102029,Cozy room in a 2B with backyard access,5155155913,UNCONFIRMED,Cristina,Queens,Astoria,40.76987,-73.92679,United States,US,0,flexible,Private room,2018.0,822,164,1.0,9.0
99338,102030,An East Williamsburg Delight,71564706996,VERIFIED,Petra,Brooklyn,Bedford-Stuyvesant,40.68335,-73.91222,United States,US,1,moderate,Private room,2015.0,455,91,4.0,36.0
99339,102031,Cozy bedroom in williamsburg,83101851929,VERIFIED,Russell,Brooklyn,Williamsburg,40.70870,-73.96710,United States,US,1,flexible,Private room,2020.0,1078,216,1.0,58.0
99340,102032,Spacious Room w/ 2 Bed,69037598918,UNCONFIRMED,Christine,Queens,Bayside,40.75047,-73.75349,United States,US,0,moderate,Private room,2007.0,103,21,7.0,40.0
99341,102040,"Room in Queens, NY, near LGA.",56457739998,VERIFIED,Sonia,Queens,East Elmhurst,40.76245,-73.87938,United States,US,1,strict,Private room,2022.0,982,196,1.0,239.0

In [144]:
# to save the data to a new csv file

data.to_csv("cleansed_airbnb_data.csv")

In [145]:
#lets read the data
pd.read_csv("cleansed_airbnb_data.csv")

,Unnamed: 0,index,NAME,HOST ID,HOST_IDENTITY_VERIFIED,HOST NAME,NEIGHBOURHOOD GROUP,NEIGHBOURHOOD,LAT,LONG,COUNTRY,COUNTRY CODE,INSTANT_BOOKABLE,CANCELLATION_POLICY,ROOM TYPE,CONSTRUCTION YEAR,PRICE,SERVICE FEE,MINIMUM NIGHTS,NUMBER OF REVIEWS
0,0,0,Clean & quiet apt home by the park,80014485718,UNCONFIRMED,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,0,strict,Private room,2020.0,966,193,10.0,9.0
1,1,1,Skylit Midtown Castle,52335172823,VERIFIED,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,0,moderate,Entire home/apt,2007.0,142,28,30.0,45.0
2,2,4,Entire Apt: Spacious Studio/Loft by central park,92037596077,VERIFIED,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,0,moderate,Entire home/apt,2009.0,204,41,10.0,9.0
3,3,5,Large Cozy 1 BR Apartment In Midtown East,45498551794,VERIFIED,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,US,1,flexible,Entire home/apt,2013.0,577,115,3.0,74.0
4,4,7,BlissArtsSpace!,90821839709,UNCONFIRMED,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,0,moderate,Private room,2009.0,1060,212,45.0,49.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99337,99337,102029,Cozy room in a 2B with backyard access,5155155913,UNCONFIRMED,Cristina,Queens,Astoria,40.76987,-73.92679,United States,US,0,flexible,Private room,2018.0,822,164,1.0,9.0
99338,99338,102030,An East Williamsburg Delight,71564706996,VERIFIED,Petra,Brooklyn,Bedford-Stuyvesant,40.68335,-73.91222,United States,US,1,moderate,Private room,2015.0,455,91,4.0,36.0
99339,99339,102031,Cozy bedroom in williamsburg,83101851929,VERIFIED,Russell,Brooklyn,Williamsburg,40.70870,-73.96710,United States,US,1,flexible,Private room,2020.0,1078,216,1.0,58.0
99340,99340,102032,Spacious Room w/ 2 Bed,69037598918,UNCONFIRMED,Christine,Queens,Bayside,40.75047,-73.75349,United States,US,0,moderate,Private room,2007.0,103,21,7.0,40.0
99341,99341,102040,"Room in Queens, NY, near LGA.",56457739998,VERIFIED,Sonia,Queens,East Elmhurst,40.76245,-73.87938,United States,US,1,strict,Private room,2022.0,982,196,1.0,239.0

In [146]:
data.to_csv("cleansed_data_wo_index", index = False)

In [147]:
pd.read_csv("cleansed_data_wo_index")

,index,NAME,HOST ID,HOST_IDENTITY_VERIFIED,HOST NAME,NEIGHBOURHOOD GROUP,NEIGHBOURHOOD,LAT,LONG,COUNTRY,COUNTRY CODE,INSTANT_BOOKABLE,CANCELLATION_POLICY,ROOM TYPE,CONSTRUCTION YEAR,PRICE,SERVICE FEE,MINIMUM NIGHTS,NUMBER OF REVIEWS
0,0,Clean & quiet apt home by the park,80014485718,UNCONFIRMED,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,0,strict,Private room,2020.0,966,193,10.0,9.0
1,1,Skylit Midtown Castle,52335172823,VERIFIED,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,0,moderate,Entire home/apt,2007.0,142,28,30.0,45.0
2,4,Entire Apt: Spacious Studio/Loft by central park,92037596077,VERIFIED,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,0,moderate,Entire home/apt,2009.0,204,41,10.0,9.0
3,5,Large Cozy 1 BR Apartment In Midtown East,45498551794,VERIFIED,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,US,1,flexible,Entire home/apt,2013.0,577,115,3.0,74.0
4,7,BlissArtsSpace!,90821839709,UNCONFIRMED,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,0,moderate,Private room,2009.0,1060,212,45.0,49.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99337,102029,Cozy room in a 2B with backyard access,5155155913,UNCONFIRMED,Cristina,Queens,Astoria,40.76987,-73.92679,United States,US,0,flexible,Private room,2018.0,822,164,1.0,9.0
99338,102030,An East Williamsburg Delight,71564706996,VERIFIED,Petra,Brooklyn,Bedford-Stuyvesant,40.68335,-73.91222,United States,US,1,moderate,Private room,2015.0,455,91,4.0,36.0
99339,102031,Cozy bedroom in williamsburg,83101851929,VERIFIED,Russell,Brooklyn,Williamsburg,40.70870,-73.96710,United States,US,1,flexible,Private room,2020.0,1078,216,1.0,58.0
99340,102032,Spacious Room w/ 2 Bed,69037598918,UNCONFIRMED,Christine,Queens,Bayside,40.75047,-73.75349,United States,US,0,moderate,Private room,2007.0,103,21,7.0,40.0
99341,102040,"Room in Queens, NY, near LGA.",56457739998,VERIFIED,Sonia,Queens,East Elmhurst,40.76245,-73.87938,United States,US,1,strict,Private room,2022.0,982,196,1.0,239.0

In [148]:
data.drop(columns = ["index"], inplace = True )

In [149]:
data

,NAME,HOST ID,HOST_IDENTITY_VERIFIED,HOST NAME,NEIGHBOURHOOD GROUP,NEIGHBOURHOOD,LAT,LONG,COUNTRY,COUNTRY CODE,INSTANT_BOOKABLE,CANCELLATION_POLICY,ROOM TYPE,CONSTRUCTION YEAR,PRICE,SERVICE FEE,MINIMUM NIGHTS,NUMBER OF REVIEWS
0,Clean & quiet apt home by the park,80014485718,UNCONFIRMED,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,0,strict,Private room,2020.0,966,193,10.0,9.0
1,Skylit Midtown Castle,52335172823,VERIFIED,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,0,moderate,Entire home/apt,2007.0,142,28,30.0,45.0
2,Entire Apt: Spacious Studio/Loft by central park,92037596077,VERIFIED,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,0,moderate,Entire home/apt,2009.0,204,41,10.0,9.0
3,Large Cozy 1 BR Apartment In Midtown East,45498551794,VERIFIED,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,US,1,flexible,Entire home/apt,2013.0,577,115,3.0,74.0
4,BlissArtsSpace!,90821839709,UNCONFIRMED,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,0,moderate,Private room,2009.0,1060,212,45.0,49.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99337,Cozy room in a 2B with backyard access,5155155913,UNCONFIRMED,Cristina,Queens,Astoria,40.76987,-73.92679,United States,US,0,flexible,Private room,2018.0,822,164,1.0,9.0
99338,An East Williamsburg Delight,71564706996,VERIFIED,Petra,Brooklyn,Bedford-Stuyvesant,40.68335,-73.91222,United States,US,1,moderate,Private room,2015.0,455,91,4.0,36.0
99339,Cozy bedroom in williamsburg,83101851929,VERIFIED,Russell,Brooklyn,Williamsburg,40.70870,-73.96710,United States,US,1,flexible,Private room,2020.0,1078,216,1.0,58.0
99340,Spacious Room w/ 2 Bed,69037598918,UNCONFIRMED,Christine,Queens,Bayside,40.75047,-73.75349,United States,US,0,moderate,Private room,2007.0,103,21,7.0,40.0
99341,"Room in Queens, NY, near LGA.",56457739998,VERIFIED,Sonia,Queens,East Elmhurst,40.76245,-73.87938,United States,US,1,strict,Private room,2022.0,982,196,1.0,239.0

In [150]:
# TO SAVE THIS TO AN EXCEL SHEET
data.to_excel("excel_cleansed_data.xlsx")

In [151]:
data.to_excel("excel_cleaned_data_false.xlsx", index = False)

In [152]:
pd.read_excel("excel_cleaned_data_false.xlsx")

,NAME,HOST ID,HOST_IDENTITY_VERIFIED,HOST NAME,NEIGHBOURHOOD GROUP,NEIGHBOURHOOD,LAT,LONG,COUNTRY,COUNTRY CODE,INSTANT_BOOKABLE,CANCELLATION_POLICY,ROOM TYPE,CONSTRUCTION YEAR,PRICE,SERVICE FEE,MINIMUM NIGHTS,NUMBER OF REVIEWS
0,Clean & quiet apt home by the park,80014485718,UNCONFIRMED,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,0,strict,Private room,2020,966,193,10,9
1,Skylit Midtown Castle,52335172823,VERIFIED,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,0,moderate,Entire home/apt,2007,142,28,30,45
2,Entire Apt: Spacious Studio/Loft by central park,92037596077,VERIFIED,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,0,moderate,Entire home/apt,2009,204,41,10,9
3,Large Cozy 1 BR Apartment In Midtown East,45498551794,VERIFIED,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,US,1,flexible,Entire home/apt,2013,577,115,3,74
4,BlissArtsSpace!,90821839709,UNCONFIRMED,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,0,moderate,Private room,2009,1060,212,45,49
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99337,Cozy room in a 2B with backyard access,5155155913,UNCONFIRMED,Cristina,Queens,Astoria,40.76987,-73.92679,United States,US,0,flexible,Private room,2018,822,164,1,9
99338,An East Williamsburg Delight,71564706996,VERIFIED,Petra,Brooklyn,Bedford-Stuyvesant,40.68335,-73.91222,United States,US,1,moderate,Private room,2015,455,91,4,36
99339,Cozy bedroom in williamsburg,83101851929,VERIFIED,Russell,Brooklyn,Williamsburg,40.70870,-73.96710,United States,US,1,flexible,Private room,2020,1078,216,1,58
99340,Spacious Room w/ 2 Bed,69037598918,UNCONFIRMED,Christine,Queens,Bayside,40.75047,-73.75349,United States,US,0,moderate,Private room,2007,103,21,7,40
99341,"Room in Queens, NY, near LGA.",56457739998,VERIFIED,Sonia,Queens,East Elmhurst,40.76245,-73.87938,United States,US,1,strict,Private room,2022,982,196,1,239